1339 Add margin to listbox button checkmark
eBay/skin pull request #1359
Opened 2021-02-09 18:55 UTC by austingardner

## Description
Added margin to listbox button dropdown to ensure checkmark isn't obscured by text.
Added example with long text to demo truncation option

## References
closes #1339 

## Screenshots
![Screen Shot 2021-02-09 at 10 43 31 AM](https://user-images.githubusercontent.com/25092249/107413067-2c580680-6ac5-11eb-9f22-4011bc5e2018.png)

2021-02-09 19:50 UTC, agliga requested changes
Actually looking at it this change is not needed.
What it looks like is we need to add the `margin-left: 8px`  in `listbox__option`

This issue came from ebayui not using `listbox-button__option`, however this will show up in `listbox__option` so we should change it there. 

<img width="1284" alt="Screen Shot 2021-02-09 at 11 50 09 AM" src="https://user-images.githubusercontent.com/1755269/107419743-fd459300-6acc-11eb-9011-65558c1cd80f.png">

2021-02-09 23:16 UTC, austingardner commented
Okay I removed the changes from listbox-button and applied them to listbox... let me know if this is what you were looking for

2021-02-10 00:07 UTC, agliga reviewed
LGTM other than removing whitespace. will merge with that.

2021-02-10 00:07 UTC, agliga commented on docs/_includes/common/listbox-button.html
> +
Remove whitespace

2021-02-10 01:01 UTC, agliga approved these changes

2021-02-10 01:01 UTC, merged

2021-02-12 21:21 UTC, ianmcburnie commented on docs/_includes/common/listbox.html
> +    <h3 id="listbox-selected">Long Option</h3>
This should be a test case / edge case under storybook only. No need for it to be on the main docs.