Infotip Spacing Fix
eBay/skin pull request #1386
Opened 2021-03-23 20:47 UTC by austingardner

## Description
Adds margin to infotip__content class. Fixes #1385 

## Screenshots

<img width="338" alt="Screen Shot 2021-03-23 at 10 43 58 AM" src="https://user-images.githubusercontent.com/25092249/112215983-3d288b80-8bde-11eb-8a42-7f1961d135d1.png">

2021-03-23 20:54 UTC, ianmcburnie approved these changes

2021-03-24 00:55 UTC, ianmcburnie requested changes
Actually, bit of a nitpick and an edge case, but this margin should probably be on the left of the close button instead, because if the close button were ever not present (I know, unlikely), we'd end up with double the amount of white space:

![Screen Shot 2021-03-23 at 5 55 09 PM](https://user-images.githubusercontent.com/38065/112237959-f6985880-8c00-11eb-9fe2-99a2f2cb5620.png)

2021-03-24 03:39 UTC, agliga commented on src/less/infotip/base/infotip.less
> +    margin-right: 16px;
Sorry i had posted earlier and accidentally left it in pending

2021-03-24 19:22 UTC, ianmcburnie approved these changes

2021-03-24 19:29 UTC, merged

2021-03-24 23:24 UTC, edvardsniedre commented
@austingardner  Should this rather be applied to `.infotip__close`?  Applying it to `.infotip .icon-btn` it also moves infotip host.

<img width="357" alt="Screenshot 2021-03-24 at 23 17 03" src="https://user-images.githubusercontent.com/7050068/112395858-16aa4380-8cf7-11eb-812f-ff70ab24b464.png">