13.3.0
eBay/skin pull request #1620
Opened 2021-12-16 21:43 UTC by austingardner

## Description

## Context

## References

## Screenshots

2021-12-16 22:51 UTC, agliga approved these changes

2021-12-16 23:35 UTC, ianmcburnie requested changes
Just noticed the progress-stepper icons are missing role=img, without that they are announced as “group” instead of “image”.Just noticed the progress-stepper icons are missing role=img, without that they are announced as “group” instead of “image”.

2021-12-17 02:24 UTC, ianmcburnie approved these changes

2021-12-17 18:58 UTC, agliga approved these changes

2021-12-20 19:27 UTC, merged