fix(textbox): icon button outline no longer goes past textbox border
eBay/skin pull request #1626
Opened 2021-12-24 03:12 UTC by austingardner

## Description
added the outline offset and updated the skin website with the `icon-btn--transparent` class

## References
closes #1625 

## Screenshots
<img width="245" alt="Screen Shot 2021-12-23 at 7 02 43 PM" src="https://user-images.githubusercontent.com/25092249/147311412-9d85090f-71ac-4b5a-a181-bc35f16bcc49.png">

2021-12-24 18:33 UTC, ianmcburnie requested changes
I think we can reduce the offset even more, maybe as far as -10px. This will also help safari which needs some adjustment:

![Screen Shot 2021-12-24 at 10 29 00 AM](https://user-images.githubusercontent.com/38065/147368850-1fef0f09-bd67-4604-baac-0c8f414ee425.png)

(also, just a reminder to always test in all our supported browsers)

2022-01-03 17:50 UTC, austingardner commented
So on Safari when I tab through, it skips the icon button and goes to the next textbox... I'm not sure why that is. Looks good on chrome and firefox though.

2022-01-03 17:53 UTC, austingardner commented
> So on Safari when I tab through, it skips the icon button and goes to the next textbox... I'm not sure why that is. Looks good on chrome and firefox though when I add the `-10px` change.

Turns out Safari disables tabbing through be default, and you have to change settings to use tab to highlight items on the page. I didn't know that! Learning moment here

2022-01-07 00:11 UTC, ianmcburnie approved these changes

2022-01-11 18:36 UTC, merged