feat: updated filter button select state
eBay/skin pull request #1828
Opened 2022-08-01 21:27 UTC by LuLaValva

Fixes #1737

- [x] This PR contains CSS changes
- [ ] This PR does not contain CSS changes

## Description

Updated selected state to reflect changes in the design system

## Notes

- My `Gemfile.lock` updated automatically so I kept it in this PR, but it may not belong here. I will remove it if necessary.
- I am not totally happy with my solution for reducing padding as I added borders, let me know if you are aware of a cleaner method.

## Screenshots

### Before:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/26027232/182249051-ec49463a-1d3c-46bb-87a2-248581e8b9bc.png">
<img width="221" alt="image" src="https://user-images.githubusercontent.com/26027232/182249087-5bc9e927-f287-49bb-a4a5-f59c009ccae9.png">
### After: 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/26027232/182249234-c5cf8dbb-e72d-4fd5-89da-7e494fdcbb08.png">
<img width="217" alt="image" src="https://user-images.githubusercontent.com/26027232/182249188-3a702233-0b91-4473-957a-51a5f7cf14d2.png">

## Checklist

- [x] I verify the build is in a non-broken state
- [x] I verify all changes are within scope of the linked issue

- [x] I regenerated all CSS files under dist folder
- [x] I tested the UI in all supported browsers
- [x] I tested the UI in dark mode and RTL mode
- [ ] I added/updated/removed Storybook coverage as appropriate

2022-08-01 21:32 UTC, ianmcburnie requested changes
Thanks for taking this one, Luke. First of all can you just remove the Gemfile.lock from this set of changes. Cheers!

2022-08-04 15:09 UTC, ArtBlue requested changes

2022-08-04 15:09 UTC, ArtBlue commented on src/less/filter-button/filter-button.less
> +    border: 1px solid;
You should include the border color via `.border-color-token` here. That should make the look and feel more "bulletproof," less reliant on inheritance, and allowed to be more easily modified for dark mode.

2022-08-04 15:09 UTC, ArtBlue commented on src/less/filter-button/filter-button.less
> +    padding: calc(@spacing-100 - 1px) calc(@spacing-200 - 1px);
No need to do these calculations to exclude the border. Just use `box-sizing: border-box;` to include the padding and border in the width.

2022-08-04 15:09 UTC, ArtBlue commented on src/less/filter-button/filter-button.less
> +    border: 1px solid;
Same comments here regarding border color and widths.

2022-08-04 15:09 UTC, ArtBlue commented on src/less/filter-menu-button/filter-menu-button.less
> +    border: 1px solid;
Same comments here regarding border color and widths.

2022-08-04 15:51 UTC, ArtBlue commented on src/less/filter-button/filter-button.less
> +    padding: calc(@spacing-100 - 1px) calc(@spacing-200 - 1px);
Also, don't forget to do the border color difference for dark mode.

2022-08-04 19:23 UTC, LuLaValva commented
Should be fixed now, thanks @ArtBlue

2022-08-05 14:27 UTC, ArtBlue reviewed
I'm seeing a diff to `dist/button/button.css` locally. Make sure you build the `css` locally and check in the changes.

2022-08-05 14:46 UTC, ArtBlue reviewed
The spacing stuff looks great! 

Some of the colors in dark mode don't match...
<img width="594" alt="image" src="https://user-images.githubusercontent.com/1675667/183101341-93a18292-3ce7-43e4-b918-5fe9d3a1e954.png">

Those that obviously stick out are the selected background colors (at rest/hover). Also, the disabled state should not change any colors on hover.

2022-08-11 19:21 UTC, LuLaValva commented
Update: This is currently blocked due to an inconsistency in design for dark mode. The dark mode page color is black (`#000000`) in Figma and in the screenshot in the comment above but it is dark gray (`#191919`) in the attached issue (#1737).

2022-08-11 22:29 UTC, agliga approved these changes
To me this looks actually fine. I'm fine with it going in like this. 
I personally don't see any issues on dark mode either

2022-08-15 15:36 UTC, ianmcburnie approved these changes

2022-08-15 18:10 UTC, merged