Disable individual items in a filter menu
eBay/skin pull request #1870
Opened 2022-09-15 00:05 UTC by LuLaValva

- Addresses ebay/ebayui-core#1693

- [x] This PR contains CSS changes
- [ ] This PR does not contain CSS changes

## Description
Change text and icon color to `color-foreground-disabled` and remove hover behavior when a class with the `--disabled` tag is added to the class list of a filter menu item.

## Notes
To test this, I manually changed the class list in the inspector as it did not seem necessary to add an example. If there should be an example I am happy to add one.

## Checklist

- [x] I verify the build is in a non-broken state
- [x] I verify all changes are within scope of the linked issue

- [x] I regenerated all CSS files under dist folder
- [ ] I tested the UI in all supported browsers
- [x] I tested the UI in dark mode and RTL mode
- [ ] I added/updated/removed Storybook coverage as appropriate

2022-09-15 00:09 UTC, ianmcburnie requested changes
We should try and leverage attributes such as `disabled` and `aria-disabled` instead of a class, where we can.

Also, it's good to have some sense of the final HTML markup - so including a story or example on the website would help with that.

2022-09-15 19:46 UTC, ianmcburnie commented on dist/filter-menu/filter-menu.css
> +button.filter-menu__footer[aria-disabled="true"],
For the button tag, we'd want to use `disabled` rather than `aria-disabled`

2022-09-17 00:27 UTC, agliga commented on dist/combobox/combobox.css
> +.combobox__option[role^="option"]:disabled,
I think for non inputs and buttons we shouldn't have disabled. It should be `aria-disabled` for those.

2022-09-17 00:41 UTC, agliga commented on dist/filter-menu/filter-menu.css
> +}
Is there a way to simplify these. Do we need all those selectors?

2022-09-17 00:41 UTC, agliga commented on dist/filter-menu/filter-menu.css
> +button.filter-menu-form__footer[type="submit"][aria-disabled="true"] {
So if it's type submit, it'll be a button. If it's not then it wont. So only for type submit we should have `:disabled` and not aria-disabled.

2022-09-30 18:44 UTC, agliga approved these changes
Actually overall looks great now. I think it's fine going in like this.

2022-09-30 18:45 UTC, agliga commented
Please target `15.1.0` and make sure the title is something like: `feat: added disaled states for menu/listbox`. The PR title will end up being the commit message in the list when you squash and merge it.

2022-10-05 15:19 UTC, ArtBlue reviewed
It's a bit hard to review this PR since it looks to have so many out-of-scope changes, which might possibly be because of the conflicts. Let's resolve the conflicts first and then review this.

2022-10-05 15:24 UTC, ArtBlue commented
@LuLaValva , when the `git` issues are resolved and conflicts ironed out, let's please make sure we run a Percy build that includes all the components/stories that were truly impacted by the change.

2022-10-11 15:25 UTC, agliga commented
Closing PR... We will merge the other one.

2022-10-11 15:25 UTC, closed without merging