feat: added scrim tokens
eBay/skin pull request #2043
Opened 2023-04-13 22:42 UTC by agliga

Fixes #2042

- [X] This PR contains CSS changes
- [ ] This PR does not contain CSS changes

## Description
* Added scrim tokens

## Screenshots
<img width="323" alt="Screen Shot 2023-04-13 at 3 41 57 PM" src="https://user-images.githubusercontent.com/1755269/231898555-36628e7c-efbc-433f-a204-33444c273beb.png">

## Checklist
- [X] I verify the build is in a non-broken state
- [X] I verify all changes are within scope of the linked issue
- [X] I regenerated all CSS files under dist folder
- [X] I tested the UI in all supported browsers
- [ ] I did a visual regression check of the components impacted by doing a Percy build and approved the build
- [X] I tested the UI in dark mode and RTL mode
- [ ] I added/updated/removed Storybook coverage as appropriate

2023-04-13 23:14 UTC, LuLaValva approved these changes
Looks good on my end

2023-04-14 17:02 UTC, ianmcburnie commented
Are we not using these tokens in our own Skin code anywhere? It would be good to switch out the current LESS variables and verify that the tokens work.

In dialog for example, I remember we needed "on/show" and "off/hide" variables to make things work:

https://github.com/eBay/skin/blob/master/src/less/mixins/private/dialog-mixins.less#L3

2023-04-14 17:02 UTC, ianmcburnie requested changes
Are we not using these tokens in our own Skin code anywhere? It would be good to switch out the current LESS variables and verify that the tokens work.

In dialog for example, I remember we needed "on/show" and "off/hide" variables to make things work:

https://github.com/eBay/skin/blob/master/src/less/mixins/private/dialog-mixins.less#L3

2023-04-18 17:13 UTC, ArtBlue commented
Ok, replaced the `LESS` vars with `CSS` props and verified things look good.

2023-04-18 17:43 UTC, LuLaValva approved these changes

2023-04-18 21:13 UTC, merged